# 程序运行级别：debug、info、warn、error
level="debug"
port="8880"
[database]
    driver="mysql"
    dsn="root:Han123456@tcp(localhost:3306)/moredoc?charset=utf8mb4&loc=Local&parseTime=true"
    showSQL=true
    prefix="mnt_"
    maxOpen=10
    maxIdle=10